spring:
  profiles:
    active: local
---
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  config:
    activate:
      on-profile: local
  sql:
    init:
      data-locations: classpath:h2Start.sql
      mode: never

